# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_28; end
module ::Anonymous_Delegator_38; end
module ::Anonymous_Delegator_8; end
module ::Spring; end
module ActionController::RespondWith; end
module ActionController::RespondWith::ClassMethods; end
module Thor::Actions; end
module Thor::Actions::ClassMethods; end
module Thor::Actions::CreateFile; end
